#+BEGIN_COMMENT
.. title: Spacemacs
.. slug: spacemacs-tips
.. date: 2020-09-01 09:34:09 UTC+02:00
.. tags: Spacemacs
.. category: productivity
.. link: 
.. description: Spacemacs tips
.. type: text

#+END_COMMENT

#+BEGIN_QUOTE
“I’m using Linux. A library that Emacs uses to
communicate with Intel hardware.”
– Erwin, /#emacs/, Freenode.
#+END_QUOTE
[[https://www.masteringemacs.org/][Thanks for quote Mickey Petersen]]

[[https://www.slant.co/topics/12/~best-programming-text-editors][Dont forget to improve other people's lifes by upvoting]]

* Introduction and motivation
As I myself prefer to work on other things than reading documentation about how
to use certain tools, I will keep this introduction very short.

In short Emacs is a universal text editing environment that is implemented as
and powered by a virtual lisp-machine. Spacemacs is a community based set of
configurations which focuses on vim-style editing with the notable - and in my
opinion genius - improvement of using the space bar as a leader key for
navigation and controlling the lisp-machine. A crucial difference between Emacs
and any other text editor is its focus on extensibility and self-documentation
which makes it the ultimate editor for hackers and community driven development.
* Spacemacs tips
** Use the Spacemacs develop branch, it is really recommended by most developers (e.g. on Spacemacs gitter)
 Follow (ALL) the steps at [[https://practicalli.github.io/spacemacs/install-spacemacs/switch-to-develop.html][the great practicalli website]] to switch to develop branch.
** Use *o* instead of *w* for editing of symbol(-name)
 In spacemacs a word(-object) is defined differently than in vim. To quickly edit
 full symbol name use =o= instead of =w= (e.g. for selecting a symbol use =v i o=).
** Quick navigation within files
 To quickly navigate inside a file use =SPC j i=. Additionally one could choose to
[[info:emacs#Specifying File Variables][set a local variable]] to start with the code folded using ~HideShow~. E.g. replace
the first line of your ~.spacemacs~ file by the following:
#+BEGIN_SRC 
;; -*- mode: emacs-lisp; eval: (hs-hide-all); lexical-binding: t -*-
#+END_SRC
** Comments
Lines can be (un)commented by selecting line with evil visual line =SPC V=
followed by =SPC ;=. Use =SPC ; ;= to directly toggle single line comments.
** Finding/discovering functionality
When looking for some kind of functionality or it's keybinding, it is often
handy to use [[https://github.com/syl20bnr/spacemacs/blob/master/doc/DOCUMENTATION.org#discovering][the self-documenting features]] of Spacemacs.

For example to find how to paste (which is called yank in emacs) in evil-insert
mode, type =M-m h d b= while in insert mode, and type "yank" (including double
quotes) to quickly find keybindings to the yank function.

As shown in the link above, there are many more =describe= functions (see =SPC h
d=). Note them well, *THEY ARE PROBABLY THE MOST IMPORTANT FUNCTIONS ONE SHOULD*
*KNOW FOR MASTERING (SPAC)EMACS*
** Some personal (nice) remappings
Paste the code from this section in the =user-config= section of your dotfile to
get the described remappings
[[https://pwmt.org/projects/zathura/][Zathura]]-style keymapping of using =J/K= for scrolling to the next/previous page
(the default =J/K= bindings are exchanged with the default bindings for jump to next/previous page)
#+BEGIN_SRC 
  (define-key evil-normal-state-map "J" nil)
  (define-key evil-normal-state-map "K" nil)
  (evil-global-set-key 'motion "J" 'evil-scroll-page-down)
  (evil-global-set-key 'motion "\C-f" 'evil-join)
  (evil-global-set-key 'motion "K" 'evil-scroll-page-up)
  (evil-global-set-key 'motion "\C-b" 'spacemacs/evil-smart-doc-lookup)
#+END_SRC
When you really get used to vim style navigation you might also prefer =C-l/C-h= over the arrow keys to scroll for scrolling forward/backward:
#+BEGIN_SRC 
  (evil-global-set-key 'insert (kbd "C-l") 'right-char)
  (evil-global-set-key 'insert (kbd "C-h") 'left-char)
#+END_SRC
It might be handy to have a shortcut to your default notes file:
#+BEGIN_SRC 
  (defun notes ()
    (interactive)
    (find-file "~/Sync/org/notes.org"))
  (spacemacs/set-leader-keys "aon" 'notes)
  (spacemacs/set-leader-keys "aos"
    (lambda () (interactive) (spacemacs/counsel-search '("rg") nil "~/Sync/org/")))
#+END_SRC
And a default shortcut to grep (deep file search) in your default notes folder
(although you might prefer to use one note file only):
#+BEGIN_SRC 
  (spacemacs/set-leader-keys "aos"
    (lambda () (interactive) (spacemacs/counsel-search '("rg") nil "~/Sync/org/")))
#+END_SRC
** Checkout and use available yasnippets in every mode 
   [[https://develop.spacemacs.org/layers/+completion/auto-completion/README.html#yasnippet][Yasnippets]] are available [[https://develop.spacemacs.org/layers/+completion/auto-completion/README.html#yasnippet][under the shortcut =SPC i s=]].
** Private packages/layers
Instead of creating private layers directly in your =.emacs.d/private/=
directory, consider to place them in a dedicated syncing directory (e.g. a
folder in your Syncthing or Dropbox directory) and then create symbolic links in
your .emacs.d/private/ directory. Even better create a github repository per layer.
** Org notes
 Create an org folder in some syncing directory (e.g. Dropbox or Syncthing).
 Subsequently in that org folder create a .projectile file. Now you can use all
 projectile functions e.g. =SPC p f= to open a file within the project, or =SPC /= to
 search withing all your notes files.
** Deep-search
 Remember that ripgrep, ag etc. ignore files in .gitignore. Therefore you can not
 simply use them to search e.g. inside of elpa packages in your .emacs.d
 directory. Instead either use =SPC s f= or use grep =SPC s g= there.
** Customizations
 - set ~dotspacemacs-distinguish-gui-tab~ to ~t~ in your .spacemacs file so you can
   jump forward with =C-i= after jumping backward with =C-o=.
** Place *(transient-bind-q-to-quit)* at the end of user-config
 I think this should be the default configuration in Spacemacs, because it is
 more vim-ish (you can find a discussion [[https://github.com/syl20bnr/spacemacs/issues/6992#issuecomment-684439951][here]]).
** Annotate PDF's
  To make annotating pdf's more comfortable, set ~pdf-annot-activate-annotation~ to
  ~t~ and add ~text-mode~ to ~evil-insert-state-modes~
** Customize buffer newline
In customize buffer, for capture template, to create a newline (instead of \n
charachter in config file), use C-j or C-o [[https://lists.gnu.org/archive/html/emacs-orgmode/2010-11/msg01006.html][reference link]]

** Spell check language
To get Dutch spell check install Dutch aspell dictionary and restart emacs (or maybe ~SPC f e R~ will work too)
** TODO Install single packages via =additional packages=
   
* Table of handy key-sequences 

| Actions                                                     | Handy key-sequence |
|-------------------------------------------------------------+--------------------|
| Quickly find recent files                                   | =SPC f r=            |
| instead of =v i w= in vim (which breaks at =-= and =_=)           | =y i o=              |
| jump quickly to word in any buffer of current frame         | =SPC j j / SPC j w=  |
| to navigate your dotfile, your org-files or just code files | =SPC j i=            |
| reformat paragraphs in org-mode (wrap lines)                | =M-q=                |
| Clear highlights after evil search                          | =SPC s c=            |
** windows
| switch window by number | SPC number / =M-number= |
| switch window (cyclic)  | SPC w w               |
** commenting
| single line    | SPC ; ;                             |
| multiple lines | visual select lines and press =SPC ;= |

* Org-mode
** Notifications
To get notifications from your org-mode items, e.g. tasks or agenda, use the
notifications library by adding =(require 'notifications)= to the
=dotspacemacs/user-config= function in your .spacemacs file.

* help/introspection
This is the most important table. You should note remember and remember to use
all options. Therefore *study this list carefully*.

*IMPORTANT COMMENTS:* 
- In info mode most of the evil-bindings are not well implemented.
Therefore it might be handy to read the Emacs documentation about how to
  navigate the info manuals.

- The describe function is extremely handy.
You should study all describe options, (especially: bindings, function, key,
  mode, variable). Although the describe function and variable functionalities
  might get useful only when writing or studying lisp, the other options are
  really handy for quickhelp lookups.

- With the /binding/ option you can quickly lookup key-bindings by fuzzy search on function name (e.g. 'upcase', 'comment', 'jump', 'delete').
- With the /key/ option you can quickly find the function name bound to a   key-sequence by searching on key sequence (e.g. =SPC l=, or =g g=).
- With the /mode/ option you can quickly get information about the current major mode (e.g. special functions and bindings for the python mode).

** help/introspection
| Go to info                             | C-h i   |
| Describe ANYTHING                      | SPC h d |
| Execute (or choose action on) function | SPC SPC |

=SPC SPC= opens =HELM M-x= you can type a name of any function and either execute
it or type =C-z= to choose from a list of alternative actions (e.g. describe, go
to definition)

When the cursor (usually called POINT in Emacs) is on a function or variable
name, one can use their respective describe key-sequences to quickly get info
about them.
